// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanlyKH.Data;

namespace QuanlyKH.Migrations
{
    [DbContext(typeof(QLkhContext))]
    [Migration("20200602060340_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuanlyKH.Models.Khachhang", b =>
                {
                    b.Property<string>("MsKH")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Nodau")
                        .HasColumnType("float");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Test")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MsKH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanlyKH.Models.Phieuthu", b =>
                {
                    b.Property<string>("MsPT")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("KhMsKH")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayThu")
                        .HasColumnType("datetime2");

                    b.Property<double>("SoTien")
                        .HasColumnType("float");

                    b.HasKey("MsPT");

                    b.HasIndex("KhMsKH");

                    b.ToTable("PhieuThu");
                });

            modelBuilder.Entity("QuanlyKH.Models.Phieuthu", b =>
                {
                    b.HasOne("QuanlyKH.Models.Khachhang", "Khachhang")
                        .WithMany()
                        .HasForeignKey("KhMsKH");
                });
#pragma warning restore 612, 618
        }
    }
}
